services:
  gis_db:
    image: pgrouting/pgrouting:16-3.5-3.7.3
    container_name: gis_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gis_tourism
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gis_tourism"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
